### ISSUE TITLE
How do I run this app?

### ISSUE THREAD

**Issue by mundayn** [microsoft/zerotrustassessment#19]
Hi all,

I missed the workshop this week unfortunately. This tool and workshop looks very interesting.

I don't see any instructions on how to use this tool?

The main page (https://microsoft.github.io/zerotrustassessment/) shows "Step 1: Run assessment", but there is no button attached to it other than "App permissions". You go to that page, and it it explains the permissions, but then does not advise how to run the tool?

Please help?

Thanks,

**Comment by GuidoBaijense** [comment]
It's currently under review by Microsoft Security team members. Until then the 'Run assessment' is not available. What you can do however, is clone the repository, re-enable the button by getting the code from a few commits back, and then 'build' or 'debug' locally. It requires you to create a multi-tenant single-page app-registration with the mentioned permissions and to change the client id in the apps code to your own registration.

**Comment by merill** [comment]
Thanks for chiming in @GuidoBaijense 

You should be able to run the assessment using PowerShell now.
