### ISSUE TITLE
A couple of bugs

### ISSUE THREAD

**Issue by HennepinCrawler** [microsoft/zerotrustassessment#22]
Application based permissions do not seem to work correctly.  When I try and use -AccessToken I get auth'd but when I run invoke-zteassessment, it throws the following error: 

ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown

I was able to get the assessment to work by adding delegated 'User.read' permission.  However, data is not fully populated. i.e., my Conditional Access Polices among other items are not showing the exported xlsx.  Is this by design?  Is there a readme of what output we should be expecting?  

I was hoping to use this for a customer, great tool.  Please let me know!  Thank you

**Comment by merill** [comment]
Can you try now with the updated version? 

The CA policies have been excluded for now while we address some issues.
