### ISSUE TITLE
Exception of type 'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' was thrown.

### ISSUE THREAD

**Issue by kraken8585** [microsoft/zerotrustassessment#228]
Version 1.1.0

https://www.powershellgallery.com/packages/ZeroTrustAssessment/1.1.0

Error thrown shortly after when Invoke-ZTAssessment was executed.

**Comment by merill** [comment]
@kraken8585 can you please try downgrading to 1.0.2 and let me know if you are seeing this issue?

```
Install-Module -Name ZeroTrustAssessment -RequiredVersion 1.0.2
```

**Comment by DavidHoerster** [comment]
@kraken8585 - also, what command line switches are you using, if any?
