### ISSUE TITLE
I cannot view information regarding data and applications

### ISSUE THREAD

**Issue by IsaacVS160883** [microsoft/zerotrustassessment#230]
I cannot view information regarding data and applications and if I have policies configured, the application only brings me results for devices and identity

![Image](https://github.com/user-attachments/assets/9adcdc7f-1948-4c1e-8e7e-c4b1790d13d5)

**Comment by DavidHoerster** [comment]
Hi @IsaacVS160883 - only Identity and Devices report back assessment information currently. As we continue to build out the other pillars, and enhance Data, these other sections will begin to light up.
