### ISSUE TITLE
What about Data, Apps, Infrastructure & Network?

### ISSUE THREAD

**Issue by jannikblatter** [microsoft/zerotrustassessment#244]
Hello,

when I am doing the generation of the excel I only get data for Identity and Devices. Am I doing something wrong or is the part of Data, Apps, Infrastructure and Network not implemented?

Thanks in advance

**Comment by DeanGross144** [comment]
I have the same question

**Comment by DavidHoerster** [comment]
Thanks for reaching out. The assessment only has checks for Identity and Devices currently, and we have roadmap tabs for Identity, Devices, and Data. We are working on additional assessments for the other pillars along with roadmap tabs for Network, Infrastructure, and Apps. We will be rolling these additional pillars and assessment checks, so please stay tuned to the website as additional pillars and checks become available. Thank you!

**Comment by DeanGross144** [comment]
@DavidHoerster can you provide any type of estimated timeline about when you are targeting the additional pillars?
